# version: '3.8'

services:
  # Backend Service - Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - lms-network
    restart: unless-stopped

  # Frontend Service - Vue.js با Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lms-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - lms-network
    restart: unless-stopped

  # Nginx Reverse Proxy (اختیاری - برای production)
  nginx-proxy:
    image: nginx:alpine
    container_name: lms-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - lms-network
    restart: unless-stopped
    profiles:
      - production

networks:
  lms-network:
    driver: bridge
    name: lms-network

volumes:
  app-data:
    driver: local